config/routes.rb
Rails.application.routes.draw do
  resources :localizacoes

  root 'localizacoes#index'

end

app/models/localizacao.rb
class Localizacao < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/localizacoes_controller.rb
class LocalizacoesController < ApplicationController
  before_action :set_localizacao, only: [:show, :edit, :update, :destroy]

  # GET /localizacoes
  # GET /localizacoes.json
  def index
    @localizacoes = Localizacao.all
  end

  # GET /localizacoes/1
  # GET /localizacoes/1.json
  def show
  end

  # GET /localizacoes/new
  def new
    @localizacao = Localizacao.new
  end

  # GET /localizacoes/1/edit
  def edit
  end

  # POST /localizacoes
  # POST /localizacoes.json
  def create
    @localizacao = Localizacao.new(localizacao_params)

    respond_to do |format|
      if @localizacao.save
        format.html { redirect_to @localizacao, notice: 'Localizacao was successfully created.' }
        format.json { render :show, status: :created, location: @localizacao }
      else
        format.html { render :new }
        format.json { render json: @localizacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localizacoes/1
  # PATCH/PUT /localizacoes/1.json
  def update
    respond_to do |format|
      if @localizacao.update(localizacao_params)
        format.html { redirect_to @localizacao, notice: 'Localizacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @localizacao }
      else
        format.html { render :edit }
        format.json { render json: @localizacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localizacoes/1
  # DELETE /localizacoes/1.json
  def destroy
    @localizacao.destroy
    respond_to do |format|
      format.html { redirect_to localizacoes_url, notice: 'Localizacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_localizacao
      @localizacao = Localizacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def localizacao_params
      params.require(:localizacao).permit(:nome, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/localizacoes_helper.rb
module LocalizacoesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MapsRails
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %script{:src => "http://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.7"}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/localizacoes/_form.html.haml
= form_for @localizacao do |f|
  - if @localizacao.errors.any?
    #error_explanation
      %h2= "#{pluralize(@localizacao.errors.count, "error")} prohibited this localizacao from being saved:"
      %ul
        - @localizacao.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nome
    = f.text_field :nome
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .actions
    = f.submit 'Save'

app/views/localizacoes/edit.html.haml
%h1 Editar localização

= render 'form'

= link_to 'Show', @localizacao
\|
= link_to 'Back', localizacoes_path

app/views/localizacoes/index.html.haml
%h1 Todas as localizações

%table
  %thead
    %tr
      %th Nome
      %th Latitude
      %th Longitude
      %th
      %th
      %th

  %tbody
    - @localizacoes.each do |localizacao|
      %tr
        %td= localizacao.nome
        %td= localizacao.latitude
        %td= localizacao.longitude
        %td= link_to 'Show', localizacao
        %td= link_to 'Edit', edit_localizacao_path(localizacao)
        %td= link_to 'Destroy', localizacao, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Localizacao', new_localizacao_path

// Aqui ficará o mapa
%hr
%br
%div{style:'width: 100%;'}
  #gmap-dropdown{style:'width: 100%; height: 450px;'}


// MAPLACE
:javascript
  new Maplace({
    locations : #{@localizacoes.to_json(:only => [ :latitude, :longitude, :nome]).gsub('latitude', 'lat').gsub('longitude', 'lon').gsub('nome', 'title')},
    //locations: #{@localizacoes.to_json(:only => [ :latitude, :longitude, :nome]).gsub('latitude', 'lat').gsub('longitude', 'lon').gsub('nome', 'title')},
    map_div: '#gmap-dropdown',
    controls_title: 'Selecione uma localização:',
    draggable : false,
    view_all_text: "Ver todos",
    type: 'polyline',
    shared: {
        zoom: 16,
        html: '#{@localizacoes.find(1).created_at.to_json}'
    }
  }).Load();

app/views/localizacoes/new.html.haml
%h1 Nova localização

= render 'form'

= link_to 'Back', localizacoes_path

app/views/localizacoes/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @localizacao.nome
%p
  %b Latitude:
  = @localizacao.latitude
%p
  %b Longitude:
  = @localizacao.longitude

= link_to 'Edit', edit_localizacao_path(@localizacao)
\|
= link_to 'Back', localizacoes_path